/* PrinceXmahto Study — from-zero expansion for every curriculum topic */
(function(){
  const L=window.PX_LESSONS||(window.PX_LESSONS={});
  const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const seen=(n,h)=>!n.sections.some(s=>s[0]===h);
  Object.keys(L).forEach(topic=>{
    const n=L[topic]; n.sections=n.sections||[];
    const overview=n.overview||'';
    const blocks=[
      ['1. Start From Zero',`<p><b>What is ${esc(topic)}?</b> Before learning formulas or exam answers, first understand what the topic means in simple language. ${esc(overview)}</p><p>Think of this chapter as a chain: <b>basic idea → parts/terms → working or rule → example → application</b>. If a new word appears, learn its meaning first instead of memorising the sentence.</p>`],
      ['2. Basic Terms You Must Know',`<p>Make a small vocabulary list while studying. For every important term, remember <b>meaning, symbol/name, unit (when applicable), purpose and one example</b>.</p><ul><li><b>Definition:</b> the exact meaning of a concept.</li><li><b>Principle:</b> the rule or law explaining how it behaves.</li><li><b>Variable/quantity:</b> something whose value can change or be measured.</li><li><b>Application:</b> where the concept is used in real life or engineering.</li></ul><div class="formula">FIRST LEARN THE WORD → THEN THE IDEA → THEN THE FORMULA → THEN THE QUESTION</div>`],
      ['3. Step-by-Step Concept Building',`<ol class="steps"><li>Read the heading and ask: “What problem does this concept solve?”</li><li>Identify its main parts, quantities, conditions or stages.</li><li>Understand the relation between those parts.</li><li>Write the governing rule, formula, diagram or process.</li><li>Work through a simple example without skipping steps.</li><li>Finally connect it to an engineering or everyday application.</li></ol><p><b>Study rule:</b> never jump directly from a definition to a difficult numerical. First do one easy example, then increase the difficulty.</p>`],
      ['4. How the Topic Works',`<p>For a process, learn it as a sequence. For a formula, learn what every symbol means. For a diagram, learn the function of every labelled part. For theory, learn <b>cause → principle → result</b>.</p><div class="diagram-note"><b class="pen-blue">Notebook flow:</b><br><span class="pen-black">INPUT / GIVEN</span> → <span class="pen-blue">PRINCIPLE / RULE</span> → <span class="pen-red">FORMULA / PROCESS</span> → <span class="pen-green">RESULT / APPLICATION</span></div>`],
      ['5. Easy Example Before Exam Level',`<p>Start with the smallest possible example. Write all given information, choose the correct rule, substitute carefully, and state the final result. If it is a theory question, first write a one-line definition and then explain the steps in order.</p><div class="formula">GIVEN → FIND → FORMULA / PRINCIPLE → SUBSTITUTION / STEPS → ANSWER → UNIT / CONCLUSION</div><p><span class="star">★</span> <b>High-priority practice:</b> be able to solve or explain one basic example from every major subtopic.</p>`],
      ['6. Common Confusions',`<ul><li>Do not confuse a definition with an application.</li><li>Do not use a formula until every symbol and condition is understood.</li><li>Do not leave diagrams unlabelled.</li><li>Do not write only the final numerical answer; show the method.</li><li>Do not memorise a comparison table without knowing why the properties differ.</li></ul><p><span class="pen-green"><b>Tip:</b></span> If you can explain the topic to a classmate in simple words, your basic understanding is usually much stronger.</p>`],
      ['7. ★ Practice While Learning',`<p>Important questions are marked <span class="star">★</span> directly beside the relevant learning point. Practise them after completing the concept instead of waiting until the end of the unit.</p><ul><li><span class="star">★</span> Explain the main definition in your own words.</li><li><span class="star">★</span> Reproduce the main formula/principle from memory.</li><li><span class="star">★</span> Draw the main labelled diagram where applicable.</li><li><span class="star">★</span> Solve one representative problem or explain one complete process.</li></ul>`],
      ['8. Quick Recall Page',`<div class="term-grid"><div><b>WHAT?</b><span>Definition and meaning</span></div><div><b>HOW?</b><span>Working, derivation or sequence</span></div><div><b>WHY?</b><span>Purpose and reason</span></div><div><b>WHERE?</b><span>Application and example</span></div></div><p><b>Final check:</b> definition ✓ &nbsp; formula/principle ✓ &nbsp; diagram ✓ &nbsp; example ✓ &nbsp; application ✓ &nbsp; ★ practice ✓</p>`]
    ];
    blocks.forEach(([h,html])=>{if(seen(n,h)) n.sections.push([h,html]);});
  });
  window.PX_LESSONS=L;
})();
