/* PrinceXmahto Study — deep handwritten notebook layer */
(function(){
  const L = window.PX_LESSONS || (window.PX_LESSONS = {});
  const esc = s => String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));

  const focus = {
    'Algebra Determinant':'determinants, matrices, Cramer’s rule, adjoint/inverse and simultaneous equations',
    'Differential Calculus':'functions, limits, continuity, first principle and differentiation rules',
    'Application of Differential Calculus':'rate of change, stationary points, maxima/minima, tangent and normal',
    'Co-ordinate Geometry':'distance, section formula, slope, straight lines and coordinate relations',
    'Probability and Statistics':'sample space, events, probability laws, mean, median, mode and data interpretation',
    'Unit and Measurements':'SI units, dimensions, significant figures, accuracy, precision, uncertainty and errors',
    'Simple Harmonic and Wave Motion':'SHM, amplitude, time period, frequency, phase and wave relations',
    'Electrostatics, Electromagnetism and Current Electricity':'charge, electric field, potential, current, resistance and magnetic effects',
    'Semiconductor Physics':'energy bands, intrinsic/extrinsic semiconductors, p-type, n-type, junction and diode',
    'Modern Physics':'photons, atomic models, radioactivity, nuclear energy and quantum ideas',
    'Basic Electrical Parameters and Concepts':'charge, current, voltage, resistance, power, energy and Ohm’s law',
    'Fundamentals of D.C. and A.C. Circuits':'DC/AC, series-parallel circuits, Kirchhoff laws and waveform quantities',
    'Magnetic Circuits and Electromagnetic Induction':'flux, flux density, MMF, reluctance, Faraday law and Lenz law',
    'Basic Electronic Components':'resistors, capacitors, inductors, diodes, LEDs and transistors',
    'Overview of Digital Electronics':'binary numbers, Boolean algebra, logic gates and truth tables',
    'Fundamentals of Artificial Intelligence':'AI, machine learning, data, models, evaluation and responsible AI',
    'Core AI Applications - Computer Vision & NLP':'classification, detection, OCR, NLP tasks and limitations',
    'Conversational AI and Generative Systems':'chatbots, intent/entity, tokens, prompting, generation, grounding and limitations',
    'Programming Logic & Computational Thinking using Python':'decomposition, abstraction, algorithms, pseudocode, variables, conditions, loops and functions',
    'Word Processing':'documents, styles, formatting, tables, page setup and PDF export',
    'Spreadsheets':'cells, formulas, references, functions, sorting, filtering, charts and interpretation',
    'Presentation Tool':'slides, layouts, typography, diagrams, charts and delivery',
    'Basics of Internet':'Internet/Web, URL, DNS, browser, server, HTTP/HTTPS and online safety',
    'Atomic Structure and Chemical Bonding':'atomic models, subatomic particles, electronic configuration, valency and chemical bonding'
  };

  /* The screenshot topic gets a genuinely expanded class-notebook treatment. */
  L['Atomic Structure and Chemical Bonding'] = {
    unit:'Unit 1',
    overview:'Atomic structure explains what an atom contains, how its particles are arranged and how electrons are distributed. Chemical bonding explains why atoms combine and how ionic, covalent and coordinate bonds are formed.',
    sections:[
      ['1. Matter → Molecule → Atom','<p><b>Matter</b> is anything that has mass and occupies space. Matter may be divided into elements, compounds and mixtures. An <b>element</b> contains one kind of atom, while a compound contains atoms of different elements chemically combined in a fixed proportion.</p><div class="formula">Matter → Element / Compound / Mixture<br>Element → Atoms<br>Atoms → Molecules / Ions</div><p class="green-note"><b>★ Exam point:</b> An atom is the basic unit of an element that retains the chemical identity of that element.</p>'],
      ['2. Structure of an Atom','<p>An atom has a very small, dense <b>nucleus</b> containing positively charged protons and neutral neutrons. Negatively charged electrons occupy regions around the nucleus called shells or energy levels.</p><div class="atom-diagram"><svg viewBox="0 0 520 260" role="img" aria-label="Simple labelled atom diagram"><circle cx="260" cy="130" r="45" fill="none" stroke="#145dcc" stroke-width="3"/><circle cx="260" cy="130" r="90" fill="none" stroke="#145dcc" stroke-width="2"/><circle cx="260" cy="130" r="135" fill="none" stroke="#145dcc" stroke-width="2"/><circle cx="260" cy="130" r="22" fill="#fff" stroke="#d52b2b" stroke-width="3"/><text x="260" y="126" text-anchor="middle" font-size="13" fill="#15171c">Nucleus</text><text x="260" y="143" text-anchor="middle" font-size="11" fill="#d52b2b">p⁺ + n⁰</text><circle cx="260" cy="40" r="7" fill="#145dcc"/><circle cx="260" cy="220" r="7" fill="#145dcc"/><circle cx="125" cy="130" r="7" fill="#145dcc"/><text x="276" y="39" font-size="12" fill="#145dcc">e⁻</text><text x="276" y="220" font-size="12" fill="#145dcc">e⁻</text><text x="105" y="126" font-size="12" fill="#145dcc">e⁻</text><text x="382" y="42" font-size="13" fill="#17834b">Shell / energy level</text><line x1="365" y1="47" x2="300" y2="65" stroke="#17834b" stroke-width="2"/></svg></div><ul><li><b>Proton:</b> charge +1, relative mass ≈ 1 u.</li><li><b>Neutron:</b> charge 0, relative mass ≈ 1 u.</li><li><b>Electron:</b> charge −1, very small relative mass.</li></ul><p><b>★ Remember:</b> In a neutral atom, number of protons = number of electrons.</p>'],
      ['3. Atomic Number and Mass Number','<p><b>Atomic number (Z)</b> is the number of protons in the nucleus. It identifies the element. For a neutral atom, it is also equal to the number of electrons.</p><p><b>Mass number (A)</b> is the total number of protons and neutrons.</p><div class="formula">Z = number of protons<br>A = protons + neutrons<br>Number of neutrons = A − Z</div><p><b>Example:</b> If an atom has A = 23 and Z = 11, then protons = 11, electrons = 11 and neutrons = 12.</p><p class="red-note"><b>★ VVI:</b> Calculate protons, electrons and neutrons when A and Z are given.</p>'],
      ['4. Isotopes, Isobars and Isotones','<p><b>Isotopes</b> are atoms of the same element having the same atomic number but different mass numbers. Therefore, they have the same number of protons but different numbers of neutrons.</p><p><b>Isobars</b> have the same mass number but different atomic numbers. <b>Isotones</b> have the same number of neutrons.</p><div class="term-grid"><div><b>Isotopes</b><span>Z same, A different</span></div><div><b>Isobars</b><span>A same, Z different</span></div><div><b>Isotones</b><span>Neutrons same</span></div><div><b>Neutral atom</b><span>protons = electrons</span></div></div><p class="green-note"><b>★ Exam point:</b> Always compare Z, A and N separately; do not decide from names alone.</p>'],
      ['5. Early Atomic Models','<p><b>Thomson model:</b> the atom was pictured as a positively charged body with electrons embedded in it.</p><p><b>Rutherford model:</b> the scattering experiment supported a small, dense, positively charged nucleus and showed that most of the atom is empty space.</p><p><b>Limitation:</b> the classical picture could not satisfactorily explain the stability of electrons around the nucleus.</p><p><b>★ VVI:</b> Draw and explain the Rutherford model and write its main conclusion.</p>'],
      ['6. Bohr Model and Energy Levels','<p>Bohr proposed that electrons occupy permitted energy levels or shells around the nucleus. An electron in an allowed stationary orbit does not continuously lose energy. Energy is absorbed or emitted when an electron moves between permitted levels.</p><div class="formula">ΔE = E₂ − E₁ = hν<br>h = Planck’s constant</div><div class="diagram-note"><b>Notebook diagram:</b><br><span class="pen-blue">K shell</span> → first energy level<br><span class="pen-blue">L shell</span> → second energy level<br><span class="pen-blue">M shell</span> → third energy level<br><span class="pen-red">Electron jumps between levels → energy change</span></div><p><b>★ Exam point:</b> Larger energy-level separation means a larger energy change for the transition.</p>'],
      ['7. Electronic Configuration','<p>Electrons are arranged in shells/energy levels. For introductory diploma chemistry, shell capacity is commonly represented by the rule <b>2n²</b>, where <b>n</b> is the shell number.</p><div class="formula">Maximum electrons in nth shell = 2n²<br>K (n=1) → 2<br>L (n=2) → 8<br>M (n=3) → 18</div><p>For many first-period and second-period examples, the outer-shell electrons are especially important because they influence chemical behaviour.</p><p><b>Example:</b> Sodium (Z=11) → 2, 8, 1. Chlorine (Z=17) → 2, 8, 7.</p><p class="red-note"><b>★ VVI:</b> Write electronic configuration for an element from its atomic number.</p>'],
      ['8. Valence Electrons and Valency','<p><b>Valence electrons</b> are electrons in the outermost occupied shell. Atoms often become more stable by losing, gaining or sharing electrons. <b>Valency</b> describes the combining capacity of an atom in a simple introductory sense.</p><div class="formula">Na: 2,8,1 → tends to lose 1 e⁻ → Na⁺<br>Cl: 2,8,7 → tends to gain 1 e⁻ → Cl⁻</div><p>Thus sodium and chlorine can form an ionic compound because electron transfer produces oppositely charged ions.</p>'],
      ['9. Why Chemical Bonds Form','<p>A chemical bond is an attractive interaction that holds atoms or ions together in a stable arrangement. Bond formation is closely related to the electronic configuration of the outer shell.</p><div class="formula">Atom → electron transfer / electron sharing → stable bonded arrangement</div><p><b>Octet idea:</b> many main-group atoms tend toward an outer shell containing eight electrons, although there are important exceptions. Treat the octet rule as a useful introductory guideline rather than a universal law.</p><p class="green-note"><b>★ Think:</b> Before identifying a bond, look at the valence electrons and ask whether electrons are transferred or shared.</p>'],
      ['10. Ionic (Electrovalent) Bond','<p>An <b>ionic bond</b> is associated with electron transfer and the electrostatic attraction between oppositely charged ions. It is commonly illustrated using a metal and a non-metal.</p><div class="formula">Na → Na⁺ + e⁻<br>Cl + e⁻ → Cl⁻<br>Na⁺ + Cl⁻ → NaCl</div><div class="diagram-note"><span class="pen-blue">Na</span> loses 1 electron → <span class="pen-red">Na⁺</span><br><span class="pen-blue">Cl</span> gains 1 electron → <span class="pen-red">Cl⁻</span><br><span class="pen-green">Opposite charges attract → ionic crystal</span></div><p><b>Typical properties:</b> ionic compounds generally form crystal lattices, often have relatively high melting points, and conduct electricity when molten or dissolved because mobile ions are present.</p><p class="red-note"><b>★ VVI:</b> Explain formation of NaCl using electron transfer and draw the electron-dot representation.</p>'],
      ['11. Covalent Bond','<p>A <b>covalent bond</b> forms when atoms share electron pairs. It is especially common between non-metal atoms. A shared pair can help each atom achieve a more stable valence-shell arrangement.</p><div class="formula">H· + ·H → H:H<br>One shared pair = single covalent bond</div><p><b>Single bond:</b> one shared pair. <b>Double bond:</b> two shared pairs. <b>Triple bond:</b> three shared pairs.</p><div class="diagram-note"><b>Lewis-style sketch:</b><br><span class="pen-blue">H</span> — <span class="pen-blue">H</span> &nbsp; → one shared pair<br><span class="pen-blue">O</span> = <span class="pen-blue">O</span> &nbsp; → two shared pairs</div><p class="green-note"><b>★ Exam point:</b> In a covalent bond, electrons are shared rather than completely transferred from one atom to another.</p>'],
      ['12. Coordinate (Dative) Bond','<p>In a <b>coordinate covalent bond</b>, the shared electron pair is supplied by the same atom. After formation, it behaves as a covalent shared pair.</p><div class="formula">Donor atom with lone pair → accepts electron-deficient centre<br>lone pair → shared pair</div><p>A common introductory example is formation of ammonium ion, where ammonia supplies a lone pair to H⁺.</p><p><b>★ VVI:</b> Define coordinate bond and explain its formation with one example.</p>'],
      ['13. Polar and Non-Polar Covalent Bonds','<p>If bonded atoms have similar attraction for the shared electrons, the bond may be described as <b>non-polar</b>. If the shared electrons are pulled more strongly toward one atom, the bond is <b>polar</b>.</p><p>This unequal sharing creates partial charges, represented as δ⁺ and δ⁻.</p><div class="formula">Unequal sharing → δ⁺—δ⁻ → bond polarity</div><p><b>Important:</b> bond polarity and overall molecular polarity are related but not always identical; molecular shape also matters.</p>'],
      ['14. Hydrogen Bonding','<p><b>Hydrogen bonding</b> is a relatively strong intermolecular interaction involving hydrogen attached to a strongly electronegative atom and attraction toward another electronegative atom having suitable electron density.</p><p>It helps explain several unusual properties of water and influences boiling point, solubility and biological structures.</p><div class="diagram-note"><span class="pen-blue">O—H</span> ··· <span class="pen-blue">O</span><br><span class="pen-red">··· = hydrogen-bond attraction</span></div><p class="green-note"><b>★ Exam point:</b> Do not confuse hydrogen bonding with an ordinary covalent bond inside the molecule.</p>'],
      ['15. Ionic vs Covalent — Notebook Comparison','<table class="note-table"><tr><th>Point</th><th>Ionic</th><th>Covalent</th></tr><tr><td>Basic idea</td><td>Electron transfer + ion attraction</td><td>Electron sharing</td></tr><tr><td>Common combination</td><td>Often metal + non-metal</td><td>Often non-metal + non-metal</td></tr><tr><td>Particles</td><td>Ions in lattice</td><td>Molecules / covalent networks</td></tr><tr><td>Conductivity</td><td>Often when molten/aqueous</td><td>Generally poor for molecular compounds</td></tr></table><p class="red-note"><b>★ VVI:</b> Differentiate ionic and covalent bonds on formation, particles and electrical conductivity.</p>'],
      ['16. Complete Chapter Connection','<div class="formula">Atomic number → electronic configuration → valence electrons<br>↓<br>electron transfer / sharing<br>↓<br>ionic / covalent / coordinate bonding<br>↓<br>properties of the substance</div><p>This is the main story of the chapter. If you understand this chain, individual definitions become easier to remember.</p><p><b>★ Final practice inside the topic:</b> (1) Find p⁺, n⁰ and e⁻ from A and Z. (2) Write shell configuration. (3) Explain NaCl formation. (4) Compare ionic and covalent bonds. (5) Explain coordinate bonding with an example.</p>']
    ],
    example:'<b>Full worked example:</b> Consider sodium, Z = 11 and A = 23. Step 1: protons = Z = 11. Step 2: for a neutral atom, electrons = 11. Step 3: neutrons = A − Z = 23 − 11 = 12. Step 4: electronic configuration = 2,8,1. Step 5: one outer electron makes loss of one electron a simple model for forming Na⁺. Chlorine has configuration 2,8,7 and can gain one electron to form Cl⁻. The electrostatic attraction between Na⁺ and Cl⁻ is the basis of the ionic-bond model for NaCl.',
    questions:['Define atom and name its three main subatomic particles.','Calculate protons, neutrons and electrons from atomic number and mass number.','Differentiate isotopes, isobars and isotones.','Explain Rutherford’s atomic model and one limitation.','Explain Bohr’s energy-level idea.','Write electronic configuration from atomic number.','Explain formation of NaCl using electron transfer.','Define covalent bond and distinguish single, double and triple bonds.','Define coordinate bond with an example.','Differentiate ionic and covalent compounds.'],
    mcqs:['Atomic number represents: <b>A)</b> number of protons &nbsp; <b>B)</b> protons + neutrons &nbsp; <b>C)</b> electrons + neutrons &nbsp; <b>D)</b> mass only','For A=23 and Z=11, neutrons are: <b>A)</b> 12 &nbsp; <b>B)</b> 11 &nbsp; <b>C)</b> 23 &nbsp; <b>D)</b> 34','Na (2,8,1) tends to: <b>A)</b> lose one electron &nbsp; <b>B)</b> gain seven electrons &nbsp; <b>C)</b> share no electrons &nbsp; <b>D)</b> lose eight electrons','A covalent bond involves: <b>A)</b> sharing of electron pair(s) &nbsp; <b>B)</b> only neutron transfer &nbsp; <b>C)</b> proton transfer &nbsp; <b>D)</b> no electrons','In a coordinate bond, the shared pair is initially supplied by: <b>A)</b> one atom &nbsp; <b>B)</b> both nuclei &nbsp; <b>C)</b> a neutron &nbsp; <b>D)</b> the crystal lattice'],
    revision:'Atom → nucleus + electrons; Z = protons; A = protons + neutrons; N = A − Z. Electronic configuration determines valence electrons. Ionic bonding is associated with electron transfer and ion attraction; covalent bonding with sharing; coordinate bonding with one-atom donation of the shared pair.'
  };

  Object.keys(L).forEach(topic=>{
    if(topic === 'Atomic Structure and Chemical Bonding') return;
    const n = L[topic];
    const f = focus[topic] || n.overview || 'the main concepts, terminology, principles, applications and examination approach';
    n.sections = n.sections || [];
    const headings = n.sections.map(s=>s[0]);
    const additions = [
      ['Notebook Study Map',`<p><b>Chapter:</b> ${esc(topic)}</p><p>The topic should be studied as a connected chain. Main scope: <b>${esc(f)}</b>.</p><div class="formula">CONCEPT → PRINCIPLE → DIAGRAM / FORMULA → EXAMPLE → APPLICATION → REVISION</div>`],
      ['How to Study This Topic',`<p>For every new term, write <b>meaning + parts/variables + principle + one example + application</b>. For numericals use <b>Given → Formula → Substitution → Result → Unit</b>. For diagrams use clear labels and arrows.</p><p class="green-note"><b>★ Exam point:</b> Learn the reason behind the formula or process instead of memorising an isolated line.</p>`],
      ['Diagram / Formula Notebook',`<div class="diagram-note"><p><span class="pen-blue">BLUE:</span> headings and labels &nbsp; <span class="pen-black">BLACK:</span> explanation &nbsp; <span class="pen-red">RED:</span> formula / key warning &nbsp; <span class="pen-green">GREEN:</span> example / result</p><div class="sketch-lines">INPUT → PROCESS → OUTPUT<br>GIVEN → FORMULA → SOLUTION<br>PART → FUNCTION → APPLICATION</div></div>`],
      ['Examination Writing Method',`<ol class="steps"><li>Identify whether the question asks to define, explain, derive, compare, calculate or draw.</li><li>Start with the governing definition/principle.</li><li>Add a labelled diagram or formula where useful.</li><li>Write steps in logical order.</li><li>Box the final numerical result and unit.</li></ol>`]
    ];
    additions.reverse().forEach(s=>{if(!headings.includes(s[0])) n.sections.unshift(s);});
  });
  window.PX_LESSONS = L;
})();
