/* PrinceXmahto Study — original CSE Semester-I AI notes */
window.PX_LESSONS = {
  'Introduction to IT Systems and Digital Technologies': {
    unit: 'Unit 1',
    overview: 'IT systems combine hardware, software, data, people, procedures and communication networks to collect, process, store and exchange information. Digital technologies represent information in discrete values, mainly using binary digits (0 and 1).',
    sections: [
      ['1. What is an IT System?', '<p>An Information Technology (IT) system is a combination of <b>hardware, software, data, users and procedures</b> used to perform useful information-processing tasks.</p><ul><li><b>Hardware:</b> physical components such as CPU, RAM, keyboard, display and storage.</li><li><b>Software:</b> operating systems and application programs.</li><li><b>Data:</b> raw facts that can be processed.</li><li><b>Users:</b> people who operate or use the system.</li><li><b>Procedures:</b> defined steps for using the system.</li><li><b>Network:</b> communication path that allows devices to exchange data.</li></ul>'],
      ['2. Data and Information', '<p><b>Data</b> means raw facts or observations. <b>Information</b> is processed or organized data that has meaning.</p><p><b>Example:</b> 72, 81 and 67 are data values. Calculating their average and reporting it as “average score = 73.3” turns the values into useful information.</p>'],
      ['3. Digital and Analog Systems', '<p>An <b>analog</b> signal varies continuously, while a <b>digital</b> signal uses discrete levels. Computers primarily process digital information.</p><div class="formula">Digital data → bits → 0 or 1<br>8 bits = 1 byte</div><p>Digital representation makes copying, processing and storing information convenient, although real-world signals such as sound and temperature are often naturally analog.</p>'],
      ['4. Main Computer Components', '<ul><li><b>CPU:</b> executes instructions and performs calculations.</li><li><b>RAM:</b> temporary working memory used by active programs.</li><li><b>Storage:</b> retains data after power is removed, e.g. SSD/HDD.</li><li><b>Input devices:</b> keyboard, mouse, camera and sensors.</li><li><b>Output devices:</b> monitor, printer and speakers.</li><li><b>Operating system:</b> manages hardware and provides services to applications.</li></ul><div class="formula">Input → Processing → Output<br>↕<br>Storage</div>'],
      ['5. Networks, Internet and Cloud Basics', '<p>A computer network connects devices so they can exchange data and share resources. The Internet is a worldwide interconnection of networks.</p><p><b>Cloud computing</b> provides computing resources such as storage or processing through networked services instead of requiring all resources to be physically present on the user device.</p>'],
      ['6. Basic Cybersecurity Hygiene', '<ul><li>Use strong, unique passwords.</li><li>Enable multi-factor authentication where available.</li><li>Keep operating systems and applications updated.</li><li>Do not open suspicious links or attachments.</li><li>Protect personal information and verify websites before entering credentials.</li><li>Keep backups of important academic files.</li></ul>']
    ],
    example: '<b>Worked example:</b> A student types a document and saves it. The keyboard supplies input, the CPU and RAM process the active program, the operating system manages resources, and the SSD stores the saved file.',
    questions: ['Define an IT system and list its major components.', 'Differentiate data and information with an example.', 'Explain digital and analog signals.', 'Write the functions of CPU, RAM and storage.', 'Explain the basic role of an operating system and a computer network.'],
    mcqs: ['Which is temporary working memory? <b>A)</b> RAM &nbsp; <b>B)</b> SSD &nbsp; <b>C)</b> Printer &nbsp; <b>D)</b> Keyboard', 'Which is a digital binary value? <b>A)</b> 0 &nbsp; <b>B)</b> 7.5 &nbsp; <b>C)</b> 3.14 &nbsp; <b>D)</b> 100°C', 'Which component executes instructions? <b>A)</b> CPU &nbsp; <b>B)</b> Monitor &nbsp; <b>C)</b> Mouse &nbsp; <b>D)</b> Speaker'],
    revision: 'IT system = hardware + software + data + users + procedures + communication. Data is raw; information is meaningful processed data. Digital systems use discrete values, commonly bits 0 and 1.'
  },
  'Fundamentals of Artificial Intelligence': {
    unit: 'Unit 2',
    overview: 'Artificial Intelligence (AI) is the field of building computational systems that can perform tasks associated with abilities such as perception, reasoning, learning, decision support and language processing.',
    sections: [
      ['1. Meaning and Goals of AI', '<p>AI systems are designed for a defined task or set of tasks. Depending on the application, an AI system may recognize patterns, classify inputs, recommend actions, understand language or generate content.</p><p>Common goals include <b>perception, reasoning, learning, prediction, planning and interaction</b>.</p>'],
      ['2. AI, Machine Learning and Deep Learning', '<p><b>AI</b> is the broad field. <b>Machine Learning (ML)</b> is an approach in which a system learns patterns from data rather than relying only on explicitly written rules. <b>Deep Learning (DL)</b> is a family of ML methods based on multi-layer neural networks.</p><div class="formula">Artificial Intelligence<br>↳ Machine Learning<br>↳ Deep Learning</div>'],
      ['3. Basic AI Workflow', '<div class="formula">Problem definition → Data/knowledge → Representation → Model or rules → Output → Evaluation</div><ol><li>Define what the system should do.</li><li>Collect or identify relevant data/knowledge.</li><li>Represent the inputs in a usable form.</li><li>Apply rules or train/select a model.</li><li>Generate a prediction, decision or response.</li><li>Evaluate results against suitable criteria.</li></ol>'],
      ['4. Learning Approaches', '<ul><li><b>Supervised learning:</b> training examples include known target labels.</li><li><b>Unsupervised learning:</b> the system looks for patterns or groups without supplied target labels.</li><li><b>Reinforcement learning:</b> an agent learns by interacting with an environment and receiving feedback such as rewards or penalties.</li></ul><p>These are introductory categories; real systems can combine several techniques.</p>'],
      ['5. Dataset, Features, Labels and Model', '<p>A <b>dataset</b> is a collection of examples. A <b>feature</b> is an input characteristic used by a model. A <b>label</b> is the known target in a labelled learning task. A <b>model</b> is a learned or specified computational representation used to produce outputs.</p><p><b>Example:</b> For classifying fruit, colour, weight and size may be features, while “apple” or “orange” may be labels.</p>'],
      ['6. Responsible AI', '<p>AI systems should be used with attention to <b>privacy, security, bias, transparency, reliability and human oversight</b>. Training data can contain errors or unfair patterns, and a model can produce incorrect results. Important decisions should therefore be checked appropriately rather than blindly accepting an AI output.</p>']
    ],
    example: '<b>Worked example:</b> Suppose a college wants to classify messages as “academic” or “other”. The problem is first defined, labelled examples are prepared, a classifier is trained, new messages are classified, and accuracy is evaluated on suitable test data.',
    questions: ['Define Artificial Intelligence.', 'Differentiate AI, Machine Learning and Deep Learning.', 'Explain a basic AI workflow.', 'Differentiate supervised, unsupervised and reinforcement learning.', 'What are features, labels and datasets?', 'List important responsible-AI considerations.'],
    mcqs: ['Machine Learning is generally considered: <b>A)</b> a subset/approach within AI &nbsp; <b>B)</b> a monitor &nbsp; <b>C)</b> a network cable &nbsp; <b>D)</b> an operating system', 'In supervised learning, training data normally contains: <b>A)</b> labels/targets &nbsp; <b>B)</b> no examples &nbsp; <b>C)</b> only passwords &nbsp; <b>D)</b> only images', 'Which is a responsible-AI concern? <b>A)</b> Privacy &nbsp; <b>B)</b> Screen brightness &nbsp; <b>C)</b> Keyboard layout &nbsp; <b>D)</b> File extension only'],
    revision: 'AI is the broad field; ML learns patterns from data; DL uses multi-layer neural networks. Workflow: problem → data/knowledge → model/rules → output → evaluation. Always consider privacy, bias, reliability and human oversight.'
  },
  'Core AI Applications - Computer Vision & NLP': {
    unit: 'Unit 3',
    overview: 'Computer Vision enables systems to extract useful information from images or video. Natural Language Processing (NLP) enables systems to process and work with human language in text or speech-related applications.',
    sections: [
      ['1. Computer Vision', '<p>Computer Vision (CV) deals with extracting information from visual inputs such as images and video.</p><ul><li><b>Image classification:</b> assign a category to an image.</li><li><b>Object detection:</b> locate objects and assign categories.</li><li><b>Segmentation:</b> assign regions or pixels to meaningful classes.</li><li><b>OCR:</b> extract written or printed text from images.</li></ul>'],
      ['2. Computer Vision Pipeline', '<div class="formula">Image/video → Acquisition → Pre-processing → Model → Prediction → Application</div><p>Pre-processing may include resizing, normalization or noise handling. The exact pipeline depends on the task and data.</p>'],
      ['3. NLP Basics', '<p>NLP concerns computational processing of human language. Typical tasks include text classification, sentiment analysis, information extraction, question answering, translation and summarization.</p><p>A simple text pipeline may include cleaning, tokenization, representation, model processing and output evaluation.</p>'],
      ['4. Tokenization and Text Representation', '<p><b>Tokenization</b> breaks text into manageable units called tokens. Depending on the system, tokens may represent words, subwords or other pieces of text.</p><div class="formula">Sentence → tokens → numerical representation → model → result</div>'],
      ['5. Vision and NLP Applications', '<ul><li>Medical-image assistance and inspection systems.</li><li>Quality checking in manufacturing.</li><li>Document scanning and OCR.</li><li>Spam or sentiment classification.</li><li>Search, translation and language assistants.</li></ul><p>Application performance depends on data quality, model design, operating conditions and evaluation.</p>'],
      ['6. Limitations', '<p>CV systems can struggle with poor lighting, unusual viewpoints or unseen objects. NLP systems can struggle with ambiguity, context, language variation and inaccurate or incomplete source information. Outputs should be validated when correctness matters.</p>']
    ],
    example: '<b>Worked example:</b> An OCR application receives a photo of a printed notice, improves the image, detects text regions, recognizes characters and returns editable text. The result should be checked because recognition errors can occur.',
    questions: ['Define Computer Vision and list its common tasks.', 'Differentiate image classification and object detection.', 'What is NLP? Give four applications.', 'Explain tokenization in simple terms.', 'Write a basic CV or NLP pipeline.', 'Mention limitations of AI-based vision and language systems.'],
    mcqs: ['Object detection normally identifies: <b>A)</b> objects and their locations &nbsp; <b>B)</b> only file size &nbsp; <b>C)</b> CPU temperature &nbsp; <b>D)</b> passwords', 'OCR is mainly used to: <b>A)</b> extract text from images &nbsp; <b>B)</b> cool a CPU &nbsp; <b>C)</b> compress RAM &nbsp; <b>D)</b> route packets', 'NLP primarily works with: <b>A)</b> human language &nbsp; <b>B)</b> electrical resistance &nbsp; <b>C)</b> screen pixels only &nbsp; <b>D)</b> battery voltage'],
    revision: 'CV works with visual data; NLP works with human language. Remember classification, detection, segmentation and OCR for CV; tokenization, classification, translation, extraction and question answering for NLP.'
  },
  'Conversational AI and Generative Systems': {
    unit: 'Unit 4',
    overview: 'Conversational AI systems interact with users through natural-language interfaces. Generative AI systems produce new content such as text, images, audio or code from learned patterns and user instructions.',
    sections: [
      ['1. Conversational AI', '<p>Conversational AI allows a user to interact with a software system using natural language. A basic chatbot can identify an input, determine an intent, use available information or tools, and return a response.</p><div class="formula">User input → Understanding → Context/knowledge → Response → User</div>'],
      ['2. Intent and Entity', '<p><b>Intent</b> represents what the user wants to accomplish. An <b>entity</b> is a useful piece of information extracted from the request.</p><p><b>Example:</b> “Show tomorrow’s timetable for CSE” has an intent related to viewing a timetable; “tomorrow” and “CSE” provide useful entities/parameters.</p>'],
      ['3. Generative AI', '<p>Generative AI creates new outputs based on patterns learned from training data and the instructions/context supplied at runtime. Examples include text generation, image generation, speech generation and code assistance.</p><p>Generated output is not automatically guaranteed to be correct or original in every respect; verification remains important.</p>'],
      ['4. Large Language Models and Tokens', '<p>Large Language Models (LLMs) process sequences of tokens and learn statistical patterns in language. A token can be a word, part of a word, punctuation or another unit depending on the tokenizer.</p><div class="formula">Prompt + context → model processing → generated tokens → response</div>'],
      ['5. Prompt, Context and Grounding', '<p>A <b>prompt</b> is an instruction or input given to a generative model. <b>Context</b> provides additional information relevant to the task. <b>Grounding</b> means connecting an answer to reliable information or a specified source so unsupported claims can be reduced.</p>'],
      ['6. Hallucination and Safe Use', '<p>An AI model may produce a confident-sounding but incorrect statement; this is commonly called a <b>hallucination</b>. For academic work, verify important facts, calculations and citations. Avoid entering unnecessary private information into AI systems.</p>']
    ],
    example: '<b>Worked example:</b> Prompt: “Explain Ohm’s law for a first-year diploma student in five points.” A good workflow specifies the audience, topic, length and desired structure, then checks the generated explanation against the textbook/curriculum.',
    questions: ['What is Conversational AI?', 'Explain intent and entity with an example.', 'Define Generative AI and give applications.', 'What are tokens in an LLM?', 'What is grounding and why is it useful?', 'What is an AI hallucination and how can students reduce its impact?'],
    mcqs: ['A prompt is mainly: <b>A)</b> an instruction/input to a generative system &nbsp; <b>B)</b> a resistor &nbsp; <b>C)</b> a monitor &nbsp; <b>D)</b> a network switch', 'Which term describes an incorrect AI-generated claim presented as if it were factual? <b>A)</b> Hallucination &nbsp; <b>B)</b> Compilation &nbsp; <b>C)</b> Encryption &nbsp; <b>D)</b> Rendering', 'Grounding helps connect an answer to: <b>A)</b> reliable information or specified sources &nbsp; <b>B)</b> keyboard LEDs &nbsp; <b>C)</b> screen size &nbsp; <b>D)</b> battery level'],
    revision: 'Conversational AI = natural-language interaction. Generative AI creates content. Remember intent/entity, prompt/context, tokens, grounding and hallucination. Verify important generated information.'
  },
  'Programming Logic & Computational Thinking using Python': {
    unit: 'Unit 5',
    overview: 'Computational thinking breaks problems into manageable steps using decomposition, pattern recognition, abstraction and algorithms. Python provides a readable way to implement these solutions.',
    sections: [
      ['1. Computational Thinking', '<ul><li><b>Decomposition:</b> break a large problem into smaller tasks.</li><li><b>Pattern recognition:</b> identify repeated structures or relationships.</li><li><b>Abstraction:</b> focus on important details and ignore irrelevant ones.</li><li><b>Algorithm design:</b> create a finite sequence of steps to solve the problem.</li></ul>'],
      ['2. Algorithm, Pseudocode and Flowchart', '<p>An <b>algorithm</b> is a clear sequence of steps for solving a problem. <b>Pseudocode</b> expresses the logic in a human-readable form. A <b>flowchart</b> represents the steps graphically using standard symbols.</p><div class="formula">Problem → Algorithm → Pseudocode/Flowchart → Python program → Test → Debug</div>'],
      ['3. Python Basics', '<p>Python uses variables to store values and supports common data types such as integers, floating-point numbers, strings, booleans, lists and dictionaries.</p><pre><code>name = "Prince"
marks = 82
passed = marks >= 40
print(name, marks, passed)</code></pre><p>Python is indentation-sensitive, so consistent indentation is important.</p>'],
      ['4. Conditions and Loops', '<pre><code>marks = 72
if marks >= 40:
    print("Pass")
else:
    print("Needs improvement")

for i in range(1, 4):
    print(i)</code></pre><p><b>if/elif/else</b> supports decisions. <b>for</b> and <b>while</b> loops repeat instructions while their conditions or iteration rules allow.</p>'],
      ['5. Functions and Collections', '<pre><code>def square(n):
    return n * n

numbers = [2, 4, 6]
print(square(numbers[0]))</code></pre><p>Functions package reusable logic. Lists store ordered collections, while dictionaries store key-value pairs.</p>'],
      ['6. Debugging and Testing', '<p><b>Syntax errors</b> prevent a program from being parsed correctly. <b>Runtime errors</b> occur during execution. <b>Logic errors</b> allow a program to run but produce an incorrect result.</p><p>Test with normal, boundary and unusual inputs. Read error messages carefully and isolate the smallest part of the program that causes the problem.</p>']
    ],
    example: '<b>Worked example:</b> To find the largest of two numbers: (1) read a and b, (2) compare them, (3) print a if a>b, otherwise print b. The same logic can be extended to more values using loops or built-in techniques.',
    questions: ['Explain decomposition, pattern recognition, abstraction and algorithm design.', 'Define algorithm and pseudocode.', 'Write a Python program using if-else to check whether a number is positive or negative.', 'Explain for and while loops with simple examples.', 'What is a function? Why is code reuse useful?', 'Differentiate syntax, runtime and logic errors.'],
    mcqs: ['Which construct is commonly used for a decision? <b>A)</b> if &nbsp; <b>B)</b> print only &nbsp; <b>C)</b> import only &nbsp; <b>D)</b> comment', 'Which Python collection is ordered and mutable? <b>A)</b> list &nbsp; <b>B)</b> integer &nbsp; <b>C)</b> boolean &nbsp; <b>D)</b> float', 'An error that produces a wrong answer while the program still runs is commonly a: <b>A)</b> logic error &nbsp; <b>B)</b> syntax error &nbsp; <b>C)</b> power failure &nbsp; <b>D)</b> font error'],
    revision: 'Computational thinking → decomposition + patterns + abstraction + algorithms. Python basics: variables, data types, operators, input/output, conditions, loops, functions and collections. Debug syntax, runtime and logic errors systematically.'
  }
};
